### ISSUE TITLE
Rogue combo points

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#92] opened 2017-03-14 22:26 UTC
**Description**: Combo points should get removed when you drop target for another one.

**Current behaviour**: Tell us what happens
Combo points stays on

**Expected behaviour**: Tell us what should happen instead
Should get removed

**Steps to reproduce the problem**:

1.  Get 1-5 combo points on any target, now target someone else, target first target again and watch combo points still be there.
2. 
3. 

**Source:** https://vanilla-twinhead.twinstar.cz/?issue=938
http://www.wowwiki.com/Patch_1.4.0
Patch 1.4.0 (2005-05-05): Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.

**Comment by Soviethammer** [comment] 2017-03-15 14:06
Combo points only gets removed if u start gettinh combo points on another target. Ths is not a bug.

**Comment by xiaoxoxo** [comment] 2017-03-15 15:13
Read source, it's currently bugged.

**Comment by modnaros** [comment] 2017-03-15 16:26
I'm sorry but no this isn't how combo points work at all Poly.

If you put combo points on a player and change target and go back, your combo points will still be there. The only way to lose combo points on a target is to generate combo points on a second target, or to use them flat out.

Lol.

**Comment by xiaoxoxo** [comment] 2017-03-15 16:28
This is not poly, and u need to look at the 2005-2006 video sources I linked.

**Comment by Soviethammer** [comment] 2017-03-15 18:30
I just think they have more important things to focus on. I dont think this is an issue, fixing this will make all rogues cry = quit, and make server have less players sadly :( i dont play rogue but i think it will ruin their class when everyone used to the bug

**Comment by Soviethammer** [comment] 2017-03-15 20:16
Nah modnaros. He is right. *{{Patch 1.4.0|note=Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.}}

And the links he linked are not private servers.

**Comment by xiaoxoxo** [comment] 2017-03-15 21:17
Modnar, obviously u don't know ur stuff. Go embarrass yourself somewhere else.

**Comment by modnaros** [comment] 2017-03-16 04:48
Yeah man I don't know my stuff when that's not how it works at all

https://puu.sh/uL11W.png

I just spoke to an old friend. You're wrong my dude.

**Comment by Soviethammer** [comment] 2017-03-16 04:58
Modnaros. You are wrong. Read patchnotes.

**Comment by modnaros** [comment] 2017-03-16 05:05
Bro, it wasn't present in 1.12.1, I'm not sure what patch it was fixed, but it wasn't there in the final patch of 1.12. You're delusional.

**Comment by Soviethammer** [comment] 2017-03-16 05:42
Go read patch 1.4 please.

**Comment by modnaros** [comment] 2017-03-16 06:33
I literally just said in my previous post that 1.4 isn't a proper reference point because it ISNT 1.12.1 and there is NO evidence of patch notes listing the fix between vanilla or TBC, despite it being fixed in 2.0.1 and 1.12.1 respectively and this is coming from the experience of multiple players who experienced retail vanilla that don't have to refer to patch notes to understand how gameplay worked. 

Like I understand source material, but when you take source material from such an early iteration of the game, especially when its a mechanic like targeting and retargeting when things were much more polished later on and this was FIXED and it's known.

**Comment by xiaoxoxo** [comment] 2017-03-16 10:51
http://wowwiki.wikia.com/wiki/Combo_point
 As of Patch 2.0.3, the rogue will not lose Combo Points upon switching targets until a point has been added to another target.

**Comment by Ipolylol** [comment] 2017-03-16 17:22
big evidence with wall of text in 2017 xD (was a great laugh when xiaoxoxo got called "Ipoly")

**Comment by robinsch** [comment] 2017-03-16 22:58
Find me a source on 1.12

**Closed by robinsch** 2017-03-16 22:58 UTC
Labels: Class - Rogue, Mechanics, On Hold, Priority - Low

**Comment by xiaoxoxo** [comment] 2017-03-17 00:06
https://www.youtube.com/watch?v=A3mBK6Wf_wQ   famous vanilla video, watch 9:50 where enemy rogues vanishes(2 combo points on), see priest sap, see enemy rogue reappear with 0 combo on. I have given plently of sources yet you want more? You can clearly see this rogue wearing ibliss so I guess case closed?

**Comment by robinsch** [comment] 2017-03-17 10:07
On PTR.
